package ipmsg;
public enum PeerStatus {
	CONNECTION_REQUEST,
	DISCONNECTION_REQUEST,
	RUNNING,CONNECTION_ACKNOWLEDGEMENT,
	MESSAGE,
	MESSAGE_WITH_FILES,
	AUDIO_CALL_REQUEST,
	AUDIO_CALL_ACCEPT,
	AUDIO_CALL_REJECT,
	AUDIO_CALL_END,
	AUDIO_CALL_BUSY,
	MESSAGE_ACKNOWLEDGEMENT,
	FILE_DOWNLOAD_REQUEST,
	FILE_DOWNLOAD_RESPONSE
};